// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function create(num) {
  if (num > 0) {
    return num;
  }
  
}

var Days = {
  create: create
};

function newDay(days) {
  var b = create(days);
  if (b !== undefined) {
    console.log(b);
    return ;
  }
  
}

exports.Days = Days;
exports.newDay = newDay;
/* No side effect */
