// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function fromString(level) {
  switch (level) {
    case "AlmostExhausted" :
        return /* AlmostExhausted */1;
    case "Exhausted" :
        return /* Exhausted */2;
    case "Sufficient" :
        return /* Sufficient */0;
    default:
      throw {
            RE_EXN_ID: "Not_found",
            Error: new Error()
          };
  }
}

exports.fromString = fromString;
/* No side effect */
