// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function fromString(level) {
  switch (level) {
    case "AlmostExceeded" :
        return /* AlmostExceeded */1;
    case "Exceeded" :
        return /* Exceeded */2;
    case "Permissible" :
        return /* Permissible */0;
    default:
      throw {
            RE_EXN_ID: "Not_found",
            Error: new Error()
          };
  }
}

exports.fromString = fromString;
/* No side effect */
