// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function fromString(wallet_type) {
  switch (wallet_type) {
    case "advance_account_wallet_usage" :
        return /* Advance_Account_Wallet_Usage */1;
    case "credit_account_wallet_usage" :
        return /* Credit_Account_Wallet_Usage */0;
    default:
      throw {
            RE_EXN_ID: "Not_found",
            Error: new Error()
          };
  }
}

exports.fromString = fromString;
/* No side effect */
