// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

function raiseError(path, message, valueOpt) {
  var value = valueOpt !== undefined ? valueOpt : "";
  return Pervasives.failwith(path + (" : " + (message + (" - " + value))));
}

exports.raiseError = raiseError;
/* No side effect */
